import {_electron as electron} from 'playwright';import assert from 'node:assert/strict';import path from 'node:path';
const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
const app=await electron.launch({executablePath:path.resolve('../../outputs/ControllerCompanion-Prototype-v05.3/ControllerCompanion.exe'),args:['--settings'],env});
try{
 let page;for(let i=0;i<100&&!page;i++){page=app.windows().find(p=>p.url().endsWith('settings.html'));if(!page)await new Promise(r=>setTimeout(r,100));}await page.waitForSelector('body[data-ready="true"]');
 await page.waitForFunction(async()=>{const s=await window.desktop.getRuntime();return s.connected&&s.devices.some(d=>d.guid.includes('8a2e00000500'));});const s=await page.evaluate(()=>window.desktop.getRuntime());assert.equal(s.error,'');const device=s.devices.find(d=>d.id===s.selectedDevice);assert.ok(device.guid.includes('8a2e00000500'));assert.equal(s.devices.filter(d=>d.guid===device.guid).length,1);await page.locator('[data-tab="controller"]').click();await page.waitForFunction(()=>document.querySelector('#controller-support').textContent.includes('需要校准'));
 await page.evaluate(()=>{window.hardwareRaw=null;window.desktop.onController(p=>{if(p.raw)window.hardwareRaw=p.raw;});});assert.equal((await page.evaluate(id=>window.desktop.controllerAction({action:'capture',id}),device.id)).ok,true);await page.waitForFunction(()=>window.hardwareRaw?.axes.length===4);const raw=await page.evaluate(()=>window.hardwareRaw);assert.equal(raw.buttons.length,10);assert.equal(raw.hats.length,1);await page.evaluate(()=>window.desktop.controllerAction({action:'cancel'}));assert.equal((await page.evaluate(()=>window.desktop.getRuntime())).calibrating,false);
 await page.locator('main').evaluate(e=>e.scrollTop=0);await page.screenshot({path:'../../outputs/RP2040识别-v05.3.png'});console.log('PASS production v5.3 settings detects real RP2040; 4-axis/10-button/1-hat capture reaches renderer; cancel releases capture.');console.log(JSON.stringify({name:device.name,guid:device.guid,mapped:device.mapped}));
}finally{await app.close();}
