export const PHYSICAL={Up:1,Down:2,Left:4,Right:8,Menu:16,View:32,L3:64,R3:128,LB:256,RB:512,A:4096,B:8192,X:16384,Y:32768,LT:65536,RT:131072};
export const LABELS={Up:'↑',Down:'↓',Left:'←',Right:'→',Menu:'≡',View:'View',L3:'L3',R3:'R3',LB:'LB',RB:'RB',A:'A',B:'B',X:'X',Y:'Y',LT:'LT',RT:'RT'};
export const ACTIONS={none:'不分配',Y:'上方字符',A:'下方字符',X:'左侧字符',B:'右侧字符',menu:'切换输入盘',space:'空格',backspace:'退格',enter:'回车',shift:'按住 Shift',lighter:'透明度 −',solid:'透明度 ＋',mouseLeft:'鼠标左键',mouseRight:'鼠标右键',mouseMiddle:'鼠标中键','key:space':'空格','key:backspace':'退格','key:enter':'回车','key:tab':'Tab','key:escape':'Esc','key:delete':'Delete','key:left':'← 方向键','key:right':'→ 方向键','key:up':'↑ 方向键','key:down':'↓ 方向键','key:home':'Home','key:end':'End','key:copy':'Ctrl+C','key:paste':'Ctrl+V','key:undo':'Ctrl+Z'};
for(const key of 'abcdefghijklmnopqrstuvwxyz0123456789')ACTIONS['key:'+key]='键盘 '+key.toUpperCase();
for(let i=1;i<=12;i++)ACTIONS['key:f'+i]='F'+i;
Object.assign(ACTIONS,{leftY:'左盘 · 上方字符',leftA:'左盘 · 下方字符',leftX:'左盘 · 左侧字符',leftB:'左盘 · 右侧字符',cycleLeft:'切换左盘',cycleRight:'切换右盘','modifier:ctrl':'按住 Ctrl','modifier:shift':'按住 Shift','key:mediaPlay':'媒体播放 / 暂停','key:mediaPrevious':'媒体上一首','key:mediaNext':'媒体下一首','layer:auxiliary':'按住使用辅助绑定','app:keyboard':'显示 / 收起转盘'});
export const DEFAULT_BINDINGS={idle:{A:'mouseLeft',B:'mouseRight',R3:'mouseMiddle'},typing:{R3:'mouseMiddle',Y:'Y',A:'A',X:'X',B:'B',Up:'space',Left:'backspace',Down:'enter',Right:'shift',Menu:'menu',LB:'lighter',RB:'solid'},dual:{R3:'mouseMiddle',Y:'Y',A:'A',X:'X',B:'B',Up:'leftY',Down:'leftA',Left:'leftX',Right:'leftB',Menu:'menu',LB:'lighter',RB:'solid'}};
export function normalizeBindings(value={}){const result={};for(const mode of ['idle','typing','dual']){result[mode]={};for(const key of Object.keys(PHYSICAL).filter(k=>k!=='L3')){const v=value?.[mode]?.[key];result[mode][key]=Object.hasOwn(ACTIONS,v)?v:DEFAULT_BINDINGS[mode][key]??'none';}}return result;}
export function normalizeAuxiliary(value={}){const result={};for(const mode of ['idle','typing','dual']){result[mode]={};for(const key of Object.keys(PHYSICAL).filter(k=>k!=='L3')){const v=value?.[mode]?.[key];result[mode][key]=Object.hasOwn(ACTIONS,v)&&v!=='layer:auxiliary'?v:'inherit';}}return result;}
export function actionsDown(buttons,bindings,mode,auxiliary={}){const base=bindings[mode]??bindings.typing;const useAux=Object.entries(base).some(([key,action])=>action==='layer:auxiliary'&&(buttons&PHYSICAL[key]));return new Set(Object.entries(base).filter(([key])=>buttons&PHYSICAL[key]).map(([key,action])=>useAux&&action!=='layer:auxiliary'&&auxiliary[mode]?.[key]&&auxiliary[mode][key]!=='inherit'?auxiliary[mode][key]:action).filter(action=>action!=='none'&&action!=='layer:auxiliary'));}
export function buttonFor(bindings,action,mode='typing'){return Object.keys(bindings[mode]).filter(k=>bindings[mode][k]===action).map(k=>LABELS[k]).join(' / ')||'—';}
