export const COPY={
 en:{appearance:'Appearance',controller:'Controller',start:'Get started',language:'Language',material:'Material',darkMode:'Dark mode',size:'Size',mode:'Mode',joystick:'Joystick',deadzoneLeft:'Left deadzone',deadzoneRight:'Right deadzone',openClose:'Open / close',leftDisc:'Left disc',rightDisc:'Right disc',wheelClosed:'Wheel closed',typing:'Typing',mouse:'Mouse',scroll:'Four-way scroll',selection:'Selection',mouseSpeed:'Mouse speed',scrollSpeed:'Scroll speed',idle:'Collapse Dial',singleInput:'Single-Key Input',dualInput:'Dual-Key Input',restore:'Restore Defaults',launch:'Launch at login',closeBehavior:'Click to close',tray:'Minimize to tray',quit:'Exit application',update:'Update',repair:'Repair',disconnected:'Controller not connected',chooseDevice:'Select controller',none:'Unassigned',space:'Space',enter:'Enter',backspace:'Backspace',shift:'Hold Shift',cyclePrevious:'Previous character style',cycleNext:'Next character style',cycleLeft:'Switch left wheel',cycleRight:'Switch right wheel',ime:'Switch input method',mouseLeft:'Left mouse button',mouseRight:'Right mouse button',mouseMiddle:'Middle mouse button',Y:'Upper character',A:'Lower character',X:'Left character',B:'Right character',leftY:'Left wheel: upper',leftA:'Left wheel: lower',leftX:'Left wheel: left',leftB:'Left wheel: right','app:keyboard':'Open / close',search:'Search actions',cancel:'Cancel',confirm:'Confirm',checking:'Checking…',latest:'You are using the latest available version.',download:'Download update',restart:'Restart and install',repairConfirm:'Download and repair all required components?',working:'Working…',complete:'Completed',failed:'The operation could not be completed. Please try again.',noIssues:'No missing or damaged components found.'},
 'zh-CN':{appearance:'外观',controller:'控制器',start:'开始使用',language:'语言',material:'材质',darkMode:'深色模式',size:'尺寸',mode:'模式',joystick:'摇杆',deadzoneLeft:'左摇杆死区',deadzoneRight:'右摇杆死区',openClose:'呼出 / 收起',leftDisc:'左盘字符',rightDisc:'右盘字符',wheelClosed:'转盘收起',typing:'输入时',mouse:'鼠标',scroll:'四向滚动',selection:'选字',mouseSpeed:'鼠标速度',scrollSpeed:'滚动速度',idle:'转盘收起',singleInput:'单盘输入',dualInput:'双盘输入',restore:'恢复默认',launch:'登录后启动',closeBehavior:'点击关闭时',tray:'隐藏到系统托盘',quit:'退出主程序',update:'检查更新',repair:'修复',disconnected:'手柄未接入',chooseDevice:'选择手柄',none:'不分配',space:'空格',enter:'回车',backspace:'退格',shift:'按住 Shift',cyclePrevious:'上一字符样式',cycleNext:'下一字符样式',cycleLeft:'切换左盘',cycleRight:'切换右盘',ime:'切换输入法',mouseLeft:'鼠标左键',mouseRight:'鼠标右键',mouseMiddle:'鼠标中键',Y:'上方字符',A:'下方字符',X:'左侧字符',B:'右侧字符',leftY:'左盘上方字符',leftA:'左盘下方字符',leftX:'左盘左侧字符',leftB:'左盘右侧字符','app:keyboard':'呼出 / 收起',search:'搜索功能',cancel:'取消',confirm:'确认',checking:'正在检查…',latest:'目前已是可用的最新版本。',download:'下载更新',restart:'立即重启安装',repairConfirm:'下载并修复全部所需组件？',working:'正在处理…',complete:'已完成',failed:'操作未完成，请重试。',noIssues:'未发现缺失或损坏的组件。'},
 ja:{appearance:'外観',controller:'コントローラー',start:'使い始める',language:'言語',material:'マテリアル',darkMode:'ダークモード',size:'サイズ',mode:'モード',joystick:'スティック',deadzoneLeft:'左デッドゾーン',deadzoneRight:'右デッドゾーン',openClose:'開く / 閉じる',leftDisc:'左ホイール',rightDisc:'右ホイール',wheelClosed:'閉じた状態',typing:'入力中',mouse:'マウス',scroll:'四方向スクロール',selection:'文字選択',mouseSpeed:'マウス速度',scrollSpeed:'スクロール速度',idle:'閉じた状態',singleInput:'シングル入力',dualInput:'デュアル入力',restore:'初期値に戻す',launch:'ログイン時に起動',closeBehavior:'閉じるボタン',tray:'トレイに隠す',quit:'アプリを終了',update:'更新確認',repair:'修復',disconnected:'未接続',chooseDevice:'コントローラーを選択',none:'未割り当て',space:'スペース',enter:'Enter',backspace:'Backspace',shift:'Shift を押す',cyclePrevious:'前の文字セット',cycleNext:'次の文字セット',cycleLeft:'左ホイール切替',cycleRight:'右ホイール切替',ime:'入力方式の切替',mouseLeft:'左クリック',mouseRight:'右クリック',mouseMiddle:'中央クリック',Y:'上の文字',A:'下の文字',X:'左の文字',B:'右の文字',leftY:'左盤：上',leftA:'左盤：下',leftX:'左盤：左',leftB:'左盤：右','app:keyboard':'開く / 閉じる',search:'機能を検索',cancel:'キャンセル',confirm:'確認',checking:'確認中…',latest:'利用可能な最新版です。',download:'更新をダウンロード',restart:'再起動して更新',repairConfirm:'必要なコンポーネントをすべてダウンロードして修復しますか？',working:'処理中…',complete:'完了',failed:'操作を完了できませんでした。再試行してください。',noIssues:'不足・破損したコンポーネントはありません。'}
};
export const text=(locale,key)=>COPY[locale]?.[key]??COPY.en[key]??key;
export function bindingText(locale,key){
 if(key.startsWith('key:'))return key.slice(4).length===1?key.slice(4).toUpperCase():({copy:'Ctrl+C',paste:'Ctrl+V',undo:'Ctrl+Z',up:'↑',down:'↓',left:'←',right:'→'})[key.slice(4)]??text(locale,key.slice(4));
 if(key.startsWith('modifier:'))return (locale==='zh-CN'?'按住 ':locale==='ja'?'押す：':'Hold ')+key.slice(9);
 return text(locale,key);
}
